### ISSUE TITLE
DrushLauncher/Drush not functionnal on non composer php projects

### ISSUE THREAD

**Issue by rhabegger** [gfi-centre-ouest/generator-docker-devbox#13]
Hi,

When selecting "php" without "composer" on "php" container, drush cannot be a project dependency : no composer require drush/drush possible ...
So if you choose to install drush launcher, it won't be able to launch drush binaries : they don't exists ... In this case, this option is de facto useless.

An enhancement would be to to force drush to be installed when "drush launcher" is checked or to add a drush option on php container when composer option is not checked to install drush (via phar or composer which is the preferred method).

FYI I've added this my Dockerfile.mo file when I need Drush on non composer projects. I think this is approximately the same code when you choose "composer" option :

```# Setup the Composer installer
RUN curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
  && curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
  && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }"

# Install Composer
RUN php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --snapshot && rm -rf /tmp/composer-setup.php
RUN apt-get update -y && apt-get install git zip unzip -y

# Github token
RUN composer config -g github-oauth.github.com db14c113decece351f1e20cf012ce0b3c8612cd5

# Install prestissimo
RUN composer global require hirak/prestissimo


# Set the Drush version.
ENV DRUSH_VERSION 8.x
# Install Drush using Composer.
RUN composer global require drush/drush:"$DRUSH_VERSION" --prefer-dist

RUN curl -fsSL -o /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar && chmod +x /usr/local/bin/drush`

The perfection would be to variabilize drush version to propose a selection of the version (7.x, 8.x, 9.x...)

Thanks in advance @Toilal

**Comment by Toilal** [comment]
J'ai commencé à bosser sur le truc, on peut en discuter demain pour la forme.
