### ISSUE TITLE
Install mariadb client fails

### ISSUE THREAD

**Issue by rhabegger** [gfi-centre-ouest/generator-docker-devbox#24]
In Stretch containers, when using standard generator mariadb-client installation script, the installation fails : it gets stucked on apt-get update after adding mariadb repo to apt lists ...

In order to install correctly mariadb client on stretch containers, this script must be used (see [here](https://downloads.mariadb.org/mariadb/repositories/#distro=Ubuntu&distro_release=bionic--ubuntu_bionic&mirror=fe_up_pt&version=10.4)) :
```
RUN apt-get update -y && apt-get install software-properties-common gnupg -y && \
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 && \
add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirrors.up.pt/pub/mariadb/repo/10.4/ubuntu bionic main' && \
apt-get update -y && apt-get install mariadb-client -y
```

**Comment by Toilal** [comment]
Enfin :)

Je m'occupe de faire une release du générateur.
